name: test_workflow
on:
  pull_request:
    branches: [ main, master ]
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: false
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.event.action }}
    - name: Check if neon evm branch is version branch
      id: is_version_neon_evm_branch
      run: |
        if [[ "${{ github.event.inputs.neon_evm_branch }}" == "" ]]; then
            echo "value=true" >> $GITHUB_OUTPUT
        fi
    - name: set neon_evm_branch
      id: param
      run: |
        echo "work"
        echo "${{ github.event.inputs.neon_evm_branch }}"
        if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/tags/".* ]]; then
          new_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/tags\///g'` 
        elif [[ ${{steps.is_version_neon_evm_branch.outputs.value}} ]]; then
          echo "YES"
        else
          new_evm_tag=${{ github.event.inputs.neon_evm_commit }}
        fi
        echo "new_evm_tag=${new_evm_tag:-'latest'}" >> $GITHUB_OUTPUT
        
        if [[ "${GITHUB_REF}" =~ "refs/tags/".* ]]; then
          proxy_tag = `echo "${GITHUB_REF}" | sed 's/refs\/tags\///g'`
        else
          proxy_tag=${GITHUB_SHA}
        fi
        echo "proxy_tag=${proxy_tag}" >> $GITHUB_OUTPUT

    - run: |
          echo ${{ steps.param.outputs.new_evm_tag }}
          echo ${{ steps.param.outputs.proxy_tag }}
