name: test_workflow
on:
  pull_request:
    branches: [ main, master ]
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: false
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: true
env:
  NEON_EVM_TAG: 'latest'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.event.action }}
        - name: Check if neon evm branch is version branch
    - id: is_version_neon_evm_branch
      run: |
        if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/heads/"[vt]{1}\d{1,2}\.\d{1,2}\.x ]]; then
            echo "value=true"
            echo "value=true" >> $GITHUB_OUTPUT
        else
            echo "value=false"
            echo "value=false" >> $GITHUB_OUTPUT
        fi
    - name: Check if neon evm branch is version branch
      run: |
          echo $NEON_EVM_TAG
          if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/tags/".* ]]; then
            neon_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/tags\///g'`
          elif [[ ${{ steps.is_version_neon_evm_branch.outputs.value}} ]]; then
            neon_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/heads\///g'`
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" == "refs/tags/master" ]]; then
            neon_evm_tag='stable'
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" == "refs/tags/develop" ]]; then
            neon_evm_tag='latest'
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" != "" ]]; then
            neon_evm_tag=${{ github.event.inputs.neon_evm_commit }}
          else
            neon_evm_tag="${NEON_EVM_TAG}"
          fi;
          echo "neon_evm_tag=${neon_evm_tag}"
          echo "neon_evm=${neon_evm_tag}" >> $GITHUB_OUTPUT

          if [[ "${{ github.event.inputs.neon_evm_commit }}" != "" ]]; then
            proxy_tag="${{ github.sha }}${{ github.event.inputs.neon_evm_commit }}"
          else
            proxy_tag="${{ github.sha }}"
          fi;
          echo "proxy_tag=${proxy_tag}"
          echo "proxy=$proxy_tag" >> $GITHUB_OUTPUT

    - run: |
          echo ${{ steps.param.outputs.new_evm_tag }}
          echo ${{ steps.param.outputs.proxy_tag }}
