name: test_workflow
on:
  pull_request:
    branches: [ main, master ]
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: false
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.event.action }}
    - name: set neon_evm_branch
      id: param
      run: |
        echo "work"
        if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/tags/".* ]]; then
          NEON_EVM_TAG=${{ github.event.inputs.neon_evm_branch }}
        else
          NEON_EVM_TAG=${{ github.event.inputs.neon_evm_commit }}
        fi
        echo "new_evm_tag=${NEON_EVM_TAG:-'latest'}"
        echo "new_evm_tag=${NEON_EVM_TAG:-'latest'}" >> $GITHUB_OUTPUT
    - run: |
          echo ${{ steps.param.outputs.new_evm_tag }}
