name: test_workflow
on:
  pull_request:
    branches: [ main, master ]
  push:
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: false
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.event.action }}
    - name: set neon_evm_branch
      id: param
      run: |
          if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/tags/".* ]]; then
            neon_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/tags\///g'` 
          else
            neon_evm_tag=${{ github.event.inputs.neon_evm_commit }}
          fi;
          echo "neon_evm=${neon_evm_tag:-'latest'}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF}" =~ "refs/tags/".* ]]; then
            proxy_tag=`echo "${GITHUB_REF}" | sed 's/refs\/tags\///g'`
          else
            proxy_tag=${GITHUB_SHA}
          fi;
          echo "proxy=$proxy_tag" >> $GITHUB_OUTPUT
          echo "test print"
    - run: |
          echo ${{ steps.param.outputs.proxy }}
