name: test_workflow1
on:
  pull_request:
    branches: [ main, master ]
    types: [ labeled, opened, reopened, synchronize]
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      full_test_suite:
        required: false
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: true
        default: ""
env:
  NEON_EVM_TAG: 'latest'
  TEST_ENV: ${{github.event.inputs.full_test_suite || secrets.AAA }}
jobs:
  test1:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${{ github.event.number }}
        echo ${{ github.event.pull_request.number }}
    - name: Check if neon evm branch is version branch
      id: is_version_neon_evm_branch
      run: |
        echo ${{github.ref}}
        a="refs/heads/t0.1.x"
        if [[ "${a}" =~ "refs/heads/"[vt][0-9]+\.[0-9]+\.x ]]; then
            echo "value=true"
            echo "value=true" >> $GITHUB_OUTPUT
        else
            echo "value=false"
            echo "value=false" >> $GITHUB_OUTPUT
        fi
    - name: Check if neon evm branch is version branch
      if: ${{!startsWith(github.event.inputs.neon_evm_branch , 'refs/tags/')  &&
            steps.is_version_neon_evm_branch.outputs.value == 'false'}}
      run: |
          echo $NEON_EVM_TAG
          t1=`git rev-parse --short e3d9f798c27bbc9a6ba2f07607bb541f018f51e3`
          echo $t1
          if [[ "${{ github.event.inputs.neon_evm_branch }}" =~ "refs/tags/".* ]]; then
            echo 'ccc'
            neon_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/tags\///g'`
          elif ${{ steps.is_version_neon_evm_branch.outputs.value }} ; then
            echo 'zzz'
            neon_evm_tag=`echo "${{ github.event.inputs.neon_evm_branch }}" | sed 's/refs\/heads\///g'`
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" == "refs/tags/master" ]]; then
            neon_evm_tag='stable'
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" == "refs/tags/develop" ]]; then
            neon_evm_tag='latest'
          elif [[ "${{ github.event.inputs.neon_evm_branch }}" != "" ]]; then
            echo 'bbb'
            neon_evm_tag=${{ github.event.inputs.neon_evm_commit }}
          else
            echo $NEON_EVM_TAG
            echo 'aaa'
            neon_evm_tag=`echo $NEON_EVM_TAG`
          fi;
          echo "neon_evm_tag=${neon_evm_tag}"
          echo "neon_evm=${neon_evm_tag}" >> $GITHUB_OUTPUT

    - run: |
          echo ${{ steps.param.outputs.new_evm_tag }}
          echo ${{ steps.param.outputs.proxy_tag }}

    - name: labels test
      if: contains(github.event.pull_request.labels.*.name, 'bug')
      run: |
       x='${{ toJson(github.event.pull_request.labels.*.name) }}'
       echo $x
