name: dep 
on:
  pull_request:
    branches: 
      - main
      - master
      - '[vt][0-9].[0-9]+.[0-9]+*'
  push:
  workflow_dispatch:
jobs:
  Job1:
    name: job1
    runs-on: ubuntu-latest
    outputs:
      flag: "aaa"
    steps:
    - name: write to console 1
      run: echo "works"
  Skipped-Job:
    name: skipped job
    runs-on: ubuntu-latest
    if: 1 != 1
    steps:
    - name: write to console 1
      run: echo "I should be skipped"
  Skipped-Job2:
    name: skipped job2
    runs-on: ubuntu-latest
    if: 1 != 1
    steps:
    - name: write to console 1
      run: echo "I should be skipped"
  report:
    name: report
    runs-on: ubuntu-latest
    if: always()
    needs: [Skipped-Job, Job1, Skipped-Job2]
    steps:
    - name: write to console 1
      run: echo "I should be skipped"
  Needs-Job:
    name: needs conditional job
    needs: [Skipped-Job, Job1, Skipped-Job2, report]
    if: always() && needs.Job1.outputs.flag == 'aaa'
    runs-on: ubuntu-latest
    steps:
      - name: write to console 2
        run: echo "Needs-Job completed"
  
