name: test_workflow
on:
  push:

env:
  NEON_EVM_TAG: 'latest'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      new_evm_tag: ${{ steps.param.outputs.new_evm_tag }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${GITHUB_REF##*/}
        echo ${{ github.ref }}
        echo ${GITHUB_REF}
        echo ${github_ref}

        echo ${{ github.event.action }}
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - run: echo "${{needs.job1.result}}"
